[package]
name = "tea-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
wgpu = "22.1.0"
vello = "0.3.0"
winit = "0.30"
pollster = "0.3"
bytemuck = { version = "1.17", features = ["derive"] }
nalgebra = { version = "0.33", features = ["bytemuck"] }
image = "0.25"
pathfinder_geometry = "0.5.1"
cosmic-text = "0.12.1"
rand = "0.8"
bitflags = "2.6"

