[package]
name = "tea-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10"
wgpu = "22"
winit = "0.30"
pollster = "0.3"
bytemuck = { version = "1.17", features = ["derive"] }
nalgebra = "0.33"
image = "0.25"
font-kit = "0.14"
pathfinder_geometry = "0.5.1"
cosmic-text = "0.12.1"
rand = "0.8"

