[package]
name = "text-render"
version = { workspace = true }
edition = "2024"
publish = false

[dependencies]
fontdb = "0.23"
fontdue = "0.9"
wgpu = { workspace = true }
nalgebra = { workspace = true }
futures = { workspace = true }

[lints]
workspace = true
